run-dist:
	./build/install/app/bin/app -h
run-app:
	./build/install/app/bin/app ~/java-project-71/app/src/main/resources/file1.json ~/java-project-71/app/src/main/resources/file2.json
report:
	./gradlew jacocoTestReport
