name: Run Gradle on PRs
on:
  push:
      branches:
        - '**'
      tags:
        - '**'

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0

      - name: jacoco-reporter
        uses: PavanMudigonda/jacoco-reporter@v4.9

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.12.0
