name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0

        with:
          java-version: '20'
          distribution: 'temurin'
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v3.0.0

        with:
          gradle-version: 8.3
          arguments: build
          build-root-directory: app
      - run: ./app/gradlew checkstyleMain
#      - run: ./gradlew checkstyleTest
#      - run: ./gradlew test
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: app/src/main/java
        with:
          coverageCommand: make report
          coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
