name: setup-jdk
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
jobs:
  gradle:
    strategy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '20'
    - run: java App.java
